version: '3.7'

services:
  ## OpenVPN ##
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - ${VOLUME_DIR}/openvpn-data/conf:/etc/openvpn

networks:
  default:
    name: openvpn-network
