version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - ${VOLUME_DIR}/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
      - traefik-network
    restart: unless-stopped
  
  pgadmin:
    user: root
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT:-5050}
    volumes:
       - ${VOLUME_DIR}/pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:5050"
    networks:
      - default
      - traefik-network
    restart: unless-stopped
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.docker.network=traefik-network
      - traefik.http.routers.pgadmin.entrypoints=web
      - traefik.http.routers.pgadmin.rule=Host(`${DOMAIN:-pgadmin.bayes-dev.lan}`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=${PGADMIN_PORT:-5050}
      # - "traefik.tcp.routers.awx.tls.passthrough=true"

networks:
  default:
    name: postgres-network
  traefik-network:
    external: true
    name: traefik-network

# volumes:
#     postgres:
#     pgadmin:
