version: '3.7'

services:
  ## Portainer ##
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - ${VOLUME_DIR}/portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: portainer-network
