version: "3.7"

services:
  ### Nextcloud database: MariaDB ###
  nextcloud-mariadb:
    image: mariadb
    container_name: nextcloud-mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ${VOLUME_DIR}/nextcloud-db:/var/lib/mysql

  ### Nextcloud cache: Redis ###
  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    restart: always

  ### Nextcloud application: Apache image ###
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis
    environment:
      ## Data directory ##
      - NEXTCLOUD_DATA_DIR=/srv/nextcloud/data

      ## Trusted domains ##
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}

      ## Database configuration ##
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

      ## Mail configuration ##
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}

      ## Apache configuration ##
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${DOMAIN}

      ## Containers link
      - MYSQL_HOST=nextcloud-mariadb
      - REDIS_HOST=nextcloud-redis
      - TRUSTED_PROXIES=traefik

      - TZ=${TZ}
    volumes:
      - ${VOLUME_DIR}/nextcloud-data/html:/var/www/html
      - ${VOLUME_DIR}/nextcloud-data/data:/srv/nextcloud/data
    networks:
      - default
      - traefik-network
    labels:
      ## Watchtower configuration: Only enable monitoring ##
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.monitor-only=true

      ## Diun configuration ##
      - diun.enable=true

      ## Traefik configuration ##
      # Enable Traefik #
      - traefik.enable=true
      - traefik.docker.network=traefik-network

      # Set entrypoint port #
      - traefik.http.services.nextcloud.loadbalancer.server.port=80

      # Set HTTP domain and HTTP -> HTTPS redirection #
      - traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nextcloud.entrypoints=web
      - traefik.http.routers.nextcloud.middlewares=https_redirect@file

      # Set HTTPS domain #
      - traefik.http.routers.nextcloud-secure.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nextcloud-secure.entrypoints=websecure
      - traefik.http.routers.nextcloud-secure.middlewares=nextcloud,nextcloud_redirect

      # Specific Nextcloud configuration #
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
      - traefik.http.middlewares.nextcloud.headers.contentTypeNosniff=true
      - traefik.http.middlewares.nextcloud.headers.browserXSSFilter=true
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/

  ### Nextcloud cron ###
  nextcloud-cron:
    image: nextcloud
    container_name: nextcloud-cron
    restart: always
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis
    entrypoint: /cron.sh
    volumes:
      - ${VOLUME_DIR}/nextcloud-data/html:/var/www/html
      - ${VOLUME_DIR}/nextcloud-data/data:/srv/nextcloud/data

networks:
  default:
    name: nextcloud-network
  traefik-network:
    external:
      name: traefik-network
