version: '3.7 '
services:
    pritunl:
        privileged: true
        ports:
            - '1194:1194/udp'  # should this be proxied through traefik?
            # - '1194:1194/tcp'
            # - '7080:80/tcp'
            # - '7443:443/tcp'
        image: jippi/pritunl
        volumes:
            - ${VOLUME_DIR}/pritunl-data:/var/lib/pritunl
        networks:
          - default
          - traefik-network
        labels:
        ## Watchtower configuration ##
        - com.centurylinklabs.watchtower.enable=true

        ## Diun configuration ##
        - diun.enable=true

        ## Traefik configuration ##
        # Enable Traefik #
        - traefik.enable=true
        - traefik.docker.network=traefik-network

        # Set entrypoint port #
        - traefik.http.services.pritunl.loadbalancer.server.port=80

        # Set HTTP domain #
        - traefik.http.routers.pritunl.entrypoints=web
        - traefik.http.routers.pritunl.rule=Host(`${DOMAIN}`)

networks:
  default:
    name: pritunl-network
  traefik-network:
    external:
      name: traefik-network


  
    