version: '3.7 '
services:
    pritunl:
        privileged: true
        restart: always
        ports:
            - '1194:1194/udp'  # should this be proxied through traefik?
            - '1194:1194/tcp'
            - '80/tcp'
            - '7443:443/tcp'
        image: jippi/pritunl
        volumes:
            - ${VOLUME_DIR}/pritunl-data:/var/lib/pritunl
        networks:
          default:
            ipv4_address: 172.18.0.3
          traefik-network:
        labels:
        ## Watchtower configuration ##
        - com.centurylinklabs.watchtower.enable=true

        ## Diun configuration ##
        - diun.enable=true

        ## Traefik configuration ##
        # Enable Traefik #
        - traefik.enable=true
        - traefik.docker.network=traefik-network

        # Set entrypoint port #
        # - traefik.http.services.pritunl.loadbalancer.server.port=443
        # # Set HTTP domain #
        # - traefik.http.routers.pritunl.entrypoints=web
        # - traefik.http.routers.pritunl.rule=Host(`${DOMAIN}`)
        # - traefik.http.routers.pritunl.middlewares=error-pages

        - "traefik.tcp.routers.myservice.rule=HostSNI(`${DOMAIN}`)"
        - "traefik.tcp.routers.myservice.tls.passthrough=true"
        - "traefik.tcp.routers.myservice.service=myservice"
        - "traefik.tcp.services.myservice.loadbalancer.server.port=443"
        - "traefik.tcp.routers.myservice.entrypoints=websecure"       

    dns-proxy-server:
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            # - '/etc/resolv.conf:/etc/resolv.conf'
        image: defreitas/dns-proxy-server
        environment: 
          - MG_REGISTER_CONTAINER_NAMES=1
          # - MG_DPS_NETWORK_AUTO_CONNECT=1
        ports:
          - 5380:5380
        networks:
          default:
            ipv4_address: 172.18.0.2
          traefik-network:
        labels:
        ## Watchtower configuration ##
        - com.centurylinklabs.watchtower.enable=true

        ## Diun configuration ##
        - diun.enable=true

        ## Traefik configuration ##
        # Enable Traefik #
        - traefik.enable=true
        - traefik.docker.network=traefik-network

        # Set entrypoint port #
        - traefik.http.services.dnsproxy.loadbalancer.server.port=5380
        # # Set HTTP domain #
        - traefik.http.routers.dnsproxy.entrypoints=web
        - traefik.http.routers.dnsproxy.rule=Host(`${DOMAIN_DNS}`)


        # - "traefik.tcp.routers.myservice.rule=HostSNI(`${DOMAIN}`)"
        # - "traefik.tcp.routers.myservice.tls.passthrough=true"
        # - "traefik.tcp.routers.myservice.service=myservice"
        # - "traefik.tcp.services.myservice.loadbalancer.server.port=443"
        # - "traefik.tcp.routers.myservice.entrypoints=websecure"  

networks:
  default:
    name: pritunl-network
    ipam:
      config:
        - subnet: 172.18.0.0/16
  traefik-network:
    external:
      name: traefik-network


  
    