version: '3.9'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ${VOLUME_DIR}/mssql-data:/var/lib/mssql/data
    environment:
      - ACCEPT_EULA=Y
#      - SA_PASSWORD=${MSSQL_ROOT_PASSWORD}
      - MSSQL_SA_PASSWORD_FILE=/run/secrets/db_password
    restart: always
    secrets: 
      - db_password

    networks:
      - default
      - traefik-network
    labels:
      ## Traefik configuration ##
      # Enable Traefik #
      - traefik.enable=true
      - traefik.docker.network=traefik-network

secrets:
  db_password:
    file: my_secret.txt

networks:
  default:
    name: mssql-network
  traefik-network:
    external: true
    name: traefik-network
